name: 3DCNN
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.4.1
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - jpeg=9d
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1m
  - packaging=21.3
  - pandas=1.3.5
  - pcre=8.45
  - pillow=8.4.0
  - pip=21.2.4
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - pytz=2021.3
  - pyyaml=6.0
  - qt=5.9.7
  - readline=8.1.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.37.0
  - tk=8.6.11
  - torchvision=0.11.2
  - tornado=6.1
  - tqdm=4.62.3
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==1.0.0
    - addict==2.4.0
    - alembic==1.7.7
    - attrs==21.4.0
    - autopage==0.5.1
    - beautifulsoup4==4.11.1
    - cachetools==5.0.0
    - captum==0.6.0
    - charset-normalizer==2.0.12
    - click==8.1.2
    - cliff==4.0.0
    - cloudpickle==2.0.0
    - cmaes==0.8.2
    - cmd2==2.4.2
    - colorlog==6.7.0
    - contextlib2==21.6.0
    - cucim==22.4.0
    - databricks-cli==0.16.6
    - defusedxml==0.7.1
    - docker==5.0.3
    - einops==0.4.1
    - entrypoints==0.4
    - filelock==3.6.0
    - fire==0.4.0
    - flask==2.1.1
    - future==0.18.2
    - gdown==4.4.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - glances==3.2.6.4
    - google-auth==2.6.5
    - google-auth-oauthlib==0.4.6
    - greenlet==1.1.2
    - grpcio==1.44.0
    - gunicorn==20.1.0
    - huggingface-hub==0.5.1
    - idna==3.3
    - imagecodecs==2022.2.22
    - imageio==2.17.0
    - importlib-metadata==4.11.3
    - itk==5.2.1.post1
    - itk-core==5.2.1.post1
    - itk-filtering==5.2.1.post1
    - itk-io==5.2.1.post1
    - itk-numerics==5.2.1.post1
    - itk-registration==5.2.1.post1
    - itk-segmentation==5.2.1.post1
    - itsdangerous==2.1.2
    - jinja2==3.1.1
    - joblib==1.1.0
    - jsonschema==4.4.0
    - lmdb==1.3.0
    - mako==1.2.0
    - markdown==3.3.6
    - markupsafe==2.1.1
    - ml-collections==0.1.1
    - mlflow==1.25.1
    - mmcv==1.6.1
    - monai==0.8.1
    - networkx==2.8
    - nibabel==3.2.2
    - oauthlib==3.2.0
    - opencv-python==4.5.5.64
    - openslide-python==1.1.2
    - optuna==3.0.2
    - pbr==5.10.0
    - prettytable==3.4.1
    - prometheus-client==0.14.1
    - prometheus-flask-exporter==0.20.1
    - protobuf==3.20.0
    - psutil==5.9.0
    - py3nvml==0.2.7
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyjwt==2.3.0
    - pyperclip==1.8.2
    - pyrsistent==0.18.1
    - pysocks==1.7.1
    - pytorch-ignite==0.4.8
    - pywavelets==1.3.0
    - querystring-parser==1.2.4
    - regex==2022.3.15
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - sacremoses==0.0.49
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - sklearn==0.0
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - sqlalchemy==1.4.35
    - sqlparse==0.4.2
    - stevedore==4.0.0
    - tabulate==0.8.9
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5
    - termcolor==1.1.0
    - threadpoolctl==3.0.0
    - tifffile==2022.4.8
    - timm==0.6.7
    - tokenizers==0.12.1
    - torchsummary==1.5.1
    - transformers==4.18.0
    - urllib3==1.26.9
    - wcwidth==0.2.5
    - websocket-client==1.3.2
    - werkzeug==2.1.1
    - xmltodict==0.13.0
    - yapf==0.32.0
    - zipp==3.8.0
prefix: /home/ubuntu/anaconda3/envs/3DCNN
